-- G57 Cloud schema
-- Run in Supabase SQL Editor.

create extension if not exists pgcrypto;

do $$ begin
  create type public.user_role as enum ('user', 'admin');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.issue_status as enum ('open', 'investigating', 'fix_in_progress', 'testing', 'fixed', 'closed');
exception when duplicate_object then null; end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  role public.user_role not null default 'user',
  created_at timestamptz not null default now()
);

create table if not exists public.issues (
  id uuid primary key default gen_random_uuid(),
  issue_number bigint generated by default as identity unique,
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  description text not null,
  problem_type text not null,
  status public.issue_status not null default 'open',
  game text not null,
  game_version text,
  driver text not null,
  emulator text not null,
  emulator_version text,
  dxvk text,
  wine text,
  proton text,
  vkd3d text,
  box64 text,
  gpu text,
  soc text,
  android_version text,
  device_model text,
  developer_note text,
  created_at timestamptz not null default now()
);

alter table public.issues add column if not exists device_model text;
alter table public.issues add column if not exists developer_note text;

create table if not exists public.attachments (
  id uuid primary key default gen_random_uuid(),
  issue_id uuid not null references public.issues(id) on delete cascade,
  type text not null check (type in ('image','video','log','file')),
  filename text not null,
  storage_path text not null unique,
  mime_type text,
  size bigint,
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  issue_id uuid references public.issues(id) on delete set null,
  title text not null,
  message text not null,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create index if not exists issues_user_id_idx on public.issues(user_id);
create index if not exists issues_status_idx on public.issues(status);
create index if not exists attachments_issue_id_idx on public.attachments(issue_id);
create index if not exists notifications_user_id_idx on public.notifications(user_id, created_at desc);

alter table public.profiles enable row level security;
alter table public.issues enable row level security;
alter table public.attachments enable row level security;
alter table public.notifications enable row level security;

create or replace function public.is_admin(uid uuid default auth.uid()) returns boolean
language sql stable security definer set search_path = public
as $$ select exists(select 1 from public.profiles p where p.id = uid and p.role = 'admin'); $$;

-- Profiles
 drop policy if exists "profile own read" on public.profiles;
 create policy "profile own read" on public.profiles for select using (id = auth.uid() or public.is_admin());
 drop policy if exists "profile insert own" on public.profiles;
 create policy "profile insert own" on public.profiles for insert with check (id = auth.uid() and role = 'user');
 drop policy if exists "profile admin update" on public.profiles;
 create policy "profile admin update" on public.profiles for update using (public.is_admin()) with check (public.is_admin());

-- Issues: users can read/delete only their own; admins can read/update/delete all.
 drop policy if exists "issue own read" on public.issues;
 create policy "issue own read" on public.issues for select using (user_id = auth.uid() or public.is_admin());
 drop policy if exists "issue own insert" on public.issues;
 create policy "issue own insert" on public.issues for insert with check (user_id = auth.uid());
 drop policy if exists "issue admin update" on public.issues;
 create policy "issue admin update" on public.issues for update using (public.is_admin()) with check (public.is_admin());
 drop policy if exists "issue own delete" on public.issues;
 create policy "issue own delete" on public.issues for delete using (user_id = auth.uid() or public.is_admin());

-- Attachments: owner/admin read; owner insert; owner/admin delete.
 drop policy if exists "attachment read" on public.attachments;
 create policy "attachment read" on public.attachments for select using (
   exists(select 1 from public.issues i where i.id = issue_id and (i.user_id = auth.uid() or public.is_admin()))
 );
 drop policy if exists "attachment insert" on public.attachments;
 create policy "attachment insert" on public.attachments for insert with check (
   exists(select 1 from public.issues i where i.id = issue_id and i.user_id = auth.uid())
 );
 drop policy if exists "attachment delete" on public.attachments;
 create policy "attachment delete" on public.attachments for delete using (
   exists(select 1 from public.issues i where i.id = issue_id and (i.user_id = auth.uid() or public.is_admin()))
 );

-- Notifications: users see/update their own; admins may see all if needed.
 drop policy if exists "notification own read" on public.notifications;
 create policy "notification own read" on public.notifications for select using (user_id = auth.uid() or public.is_admin());
 drop policy if exists "notification own update" on public.notifications;
 create policy "notification own update" on public.notifications for update using (user_id = auth.uid() or public.is_admin()) with check (user_id = auth.uid() or public.is_admin());

-- Private storage bucket.
insert into storage.buckets (id, name, public)
values ('issue-files', 'issue-files', false)
on conflict (id) do update set public = false;

-- Storage object policies. Object path format: <issue-uuid>/<file>.
drop policy if exists "issue files insert" on storage.objects;
create policy "issue files insert" on storage.objects for insert to authenticated with check (
  bucket_id = 'issue-files' and exists (
    select 1 from public.issues i
    where i.id::text = split_part(name, '/', 1) and i.user_id = auth.uid()
  )
);

drop policy if exists "issue files read" on storage.objects;
create policy "issue files read" on storage.objects for select to authenticated using (
  bucket_id = 'issue-files' and exists (
    select 1 from public.issues i
    where i.id::text = split_part(name, '/', 1) and (i.user_id = auth.uid() or public.is_admin())
  )
);

drop policy if exists "issue files delete" on storage.objects;
create policy "issue files delete" on storage.objects for delete to authenticated using (
  bucket_id = 'issue-files' and exists (
    select 1 from public.issues i
    where i.id::text = split_part(name, '/', 1) and (i.user_id = auth.uid() or public.is_admin())
  )
);

-- Auto-create profile after Auth signup, including username-only anonymous users.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $
declare
  chosen_username text;
begin
  chosen_username := lower(trim(coalesce(
    new.raw_user_meta_data->>'username',
    case when new.email is not null then split_part(new.email, '@', 1) end,
    'user-' || left(new.id::text, 8)
  )));

  insert into public.profiles (id, username)
  values (new.id, chosen_username);

  return new;
end;
$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Notify the user exactly once when an issue transitions into Fixed/Closed.
create or replace function public.notify_issue_resolved()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if (new.status in ('fixed','closed')) and (old.status not in ('fixed','closed')) then
    insert into public.notifications (user_id, issue_id, title, message)
    values (
      new.user_id,
      new.id,
      'Issue #' || new.issue_number || ' resolved',
      'The developer marked your "' || new.title || '" issue as resolved. Open G57 to see the final status and developer note.'
    );
  end if;
  return new;
end;
$$;

drop trigger if exists issue_resolved_notification on public.issues;
create trigger issue_resolved_notification
after update of status on public.issues
for each row execute procedure public.notify_issue_resolved();

-- ADMIN SETUP:
-- Create the real admin in Supabase Auth using an internal email:
-- <admin_username>@g57.app
-- Then promote that profile:
-- update public.profiles set role = 'admin' where username = '<admin_username>';
--
-- USER ACCESS:
-- The Android app uses Supabase Anonymous Sign-Ins. The user enters only
-- a unique username; no email or password is shown or required.
-- Enable Authentication -> Sign In / Providers -> Anonymous Sign-Ins
-- in the Supabase dashboard before using username-only User access.
